/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pong;

import gameNet.GameInfo;

/**
 *
 * @author ijaaztello
 */
public class Game extends javax.swing.JFrame {
    MyUserInterface myUserInterface = new MyUserInterface();
    GameInfo myGameInfo;
    boolean ON = false;
    boolean clientServer = false;
    MyMain myMain;
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
	myMain = new MyMain();
	myUserInterface = new MyUserInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                GameSetup = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jTextField1 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jTabbedPane2 = new javax.swing.JTabbedPane();
                serverPanel = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                serverIpAddr = new javax.swing.JLabel();
                serverPort = new javax.swing.JLabel();
                clientPanel = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                clientIpAddr = new javax.swing.JTextField();
                clientPort = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setFocusTraversalPolicyProvider(true);
                setPreferredSize(new java.awt.Dimension(800, 400));
                setResizable(false);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {
                                formWindowClosed(evt);
                        }
                });

                GameSetup.setPreferredSize(new java.awt.Dimension(800, 400));

                jButton1.setLabel("Start Game");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jTextField1.setText("Name");
                jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                jTextField1.setFocusTraversalKeysEnabled(false);
                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1ActionPerformed(evt);
                        }
                });

                jLabel1.setText("Name");

                jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                jTabbedPane2StateChanged(evt);
                        }
                });
                jTabbedPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                jTabbedPane2ComponentShown(evt);
                        }
                });

                serverPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                serverPanelComponentShown(evt);
                        }
                });

                jLabel3.setText("IP Address");

                jLabel4.setText("Port");

                serverIpAddr.setText("10.0.0.0");

                serverPort.setText("54321");

                javax.swing.GroupLayout serverPanelLayout = new javax.swing.GroupLayout(serverPanel);
                serverPanel.setLayout(serverPanelLayout);
                serverPanelLayout.setHorizontalGroup(
                        serverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serverPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(serverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(serverPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(serverPort)
                                                .addGap(93, 93, 93))
                                        .addGroup(serverPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(serverIpAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(74, 74, 74))))
                );
                serverPanelLayout.setVerticalGroup(
                        serverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serverPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(serverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(serverIpAddr))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(serverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(serverPort))
                                .addContainerGap(23, Short.MAX_VALUE))
                );

                jTabbedPane2.addTab("Server", serverPanel);

                clientPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                clientPanelComponentShown(evt);
                        }
                });

                jLabel8.setText("Port");

                jLabel9.setText("IP Address");

                clientIpAddr.setText("10.0.0.0");
                clientIpAddr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                clientIpAddr.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clientIpAddrActionPerformed(evt);
                        }
                });

                clientPort.setText("54321");
                clientPort.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clientPortActionPerformed(evt);
                        }
                });

                jLabel2.setText("SUCCESS!!");

                javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
                clientPanel.setLayout(clientPanelLayout);
                clientPanelLayout.setHorizontalGroup(
                        clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clientPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addGap(50, 50, 50))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clientPanelLayout.createSequentialGroup()
                                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(93, 93, 93))
                        .addGroup(clientPanelLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clientIpAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                clientPanelLayout.setVerticalGroup(
                        clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(clientIpAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(clientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45))
                );

                clientIpAddr.getAccessibleContext().setAccessibleName("");
                clientIpAddr.getAccessibleContext().setAccessibleDescription("");

                jTabbedPane2.addTab("Client", clientPanel);

                javax.swing.GroupLayout GameSetupLayout = new javax.swing.GroupLayout(GameSetup);
                GameSetup.setLayout(GameSetupLayout);
                GameSetupLayout.setHorizontalGroup(
                        GameSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameSetupLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(50, 50, 50))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameSetupLayout.createSequentialGroup()
                                .addGap(0, 108, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                );
                GameSetupLayout.setVerticalGroup(
                        GameSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GameSetupLayout.createSequentialGroup()
                                .addGroup(GameSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(GameSetupLayout.createSequentialGroup()
                                                .addGap(141, 141, 141)
                                                .addGroup(GameSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addGap(108, 108, 108))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameSetupLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)))
                                .addComponent(jButton1)
                                .addContainerGap(96, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GameSetup, 788, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GameSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                GameSetup.getAccessibleContext().setAccessibleName("");

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
            System.out.println("Client is exitting game");
	    myUserInterface.exitProgram();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String playerName = jTextField1.getText();
	String ipAddr;
	int port;
	boolean createServer;
	if(clientServer) {
		ipAddr = clientIpAddr.getText();
		String portString = clientPort.getText();
		port = Integer.parseInt(portString);
		createServer = false;
	} else {
		playerName = jTextField1.getText();
		createServer = true;
		ipAddr = null;
		port = 0;
	}
	myGameInfo = new GameInfo(playerName, createServer, ipAddr, port);
	System.out.println(myGameInfo);
	GameSetup.setVisible(false);
	add(myUserInterface);
	myMain.enterGame(myUserInterface, myGameInfo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

        private void clientIpAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIpAddrActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_clientIpAddrActionPerformed

        private void clientPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientPortActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_clientPortActionPerformed

        private void jTabbedPane2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane2ComponentShown
                // TODO add your handling code here:
		System.out.println(evt.paramString());
        }//GEN-LAST:event_jTabbedPane2ComponentShown

        private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
                // TODO add your handling code here:
        }//GEN-LAST:event_jTabbedPane2StateChanged

        private void serverPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_serverPanelComponentShown
                // TODO add your handling code here:
		clientServer = false;
        }//GEN-LAST:event_serverPanelComponentShown

        private void clientPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_clientPanelComponentShown
                // TODO add your handling code here:
		clientServer = true;
        }//GEN-LAST:event_clientPanelComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel GameSetup;
        private javax.swing.JTextField clientIpAddr;
        private javax.swing.JPanel clientPanel;
        private javax.swing.JTextField clientPort;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JTabbedPane jTabbedPane2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JLabel serverIpAddr;
        private javax.swing.JPanel serverPanel;
        private javax.swing.JLabel serverPort;
        // End of variables declaration//GEN-END:variables
}
